### ISSUE TITLE
Additional Information Request

### ISSUE THREAD

**Issue by jdw1953** [dankar/gpsdo-fw#4]
This really is not an issue or request for another feature, fix bug, or report a specific curiosity in behavior… Just a little more information on use of GPSDO after implementing changes.
It appears that your effort has potential to vastly improve type of information being displayed. I think considerable interest from others are likely to follow. Keep up good work!! Just a thought that it might help us newbies to provide a short text document describing the functionality intent of the original menu displays. For example my menu currently allows selection  for CONTRAST, OFFSET, and PWMSET.
 My own inexperience with GPSDO devices result in confusion as what the fundamental intent of these 3 menu driven adjustments are supposed to achieve (such as part of calibration when antenna is connected or do they just influence the output). If new menu items are subsequently added what is intent. Any other notes on operating it such as what becomes of calibration and manual changes done through menus if turned off or removal of power cord.

**Comment by dankar** [comment]
I'm not sure I can provide any more information about the original firmware than what is in the manual for that.

I've been planning on adding the contrast adjustment (this just modifies the contrast of the LCD) to my firmware as well, but haven't gotten round to it yet.
